### ISSUE TITLE
What release of the Berkeley Parser will be used in the evaluation?  Can we have the source code?

### ISSUE THREAD

**Issue by axch** [GaloisInc/ppaml-cp5#8]
We are attempting to get an end-to-end development run of the
evaluation process for CP5, and running into the following problem:

Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/berkeley/nlp/PCFGLA/GrammarTrainer : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

which seems to indicate that the class files in the distributed
BerkeleyParser-1.7.jar require Java 8.  This is unfortunate, because
the newest Java runtime environment packaged for Ubuntu 14.04 LTS is
OpenJDK 7.

This dependency is also surprising.  The latest public release of the
Berkeley Parser that we were able to find is quite different:
- Was released in October 2012
- Requires only Java 7 (and runs in our environment)
- Has a somewhat different user interface
- Is located at https://code.google.com/p/berkeleyparser/downloads/list
- Is confusingly also named BerkeleyParser-1.7.jar

Could you please

1) Clarify the version of the Berkeley Parser that will be used for
   the evaluation?

2) Distribute its source code?

3) If the dependence on Java 8 is non-essential, build a .jar that
   runs in Java 7?

**Comment by hhexiy** [comment]
Hi,

The original BerkeleyParser-1.7.jar is modified to read grammar in text
format.

It does not require Java 8, however, the original BerkeleyParser uses some
generic class whose type cannot be inferred by javac. It can be compiled by
Eclipse though. I don't have Eclipse installed right now, but I'll look
into this. Meanwhile, I've added a new jar BerkeleyParser-ppaml-1.8.jar to
avoid confusion in names, and BerkeleyParser-ppaml-1.8_source.jar if you
are interested in compiling it on your machine.

He

**Comment by axch** [comment]
Could you push that so we can try it out?

**Comment by hhexiy** [comment]
oops, forgot to push.. done now.

**Comment by probinso** [comment]
Just a heads up, 

We are presently using Java 1.8 on our Ubuntu 14.04.2 LTS evaluation machine, this is mentioned in the submission requirements document and capture in the changelog.
```script
$ sudo add-apt-repository ppa:openjdk-r/ppa
``` 
should make it easy to gain access to this dependency

**Comment by axch** [comment]
Thanks; BerkeleyParser-ppaml-1.8.jar ran without further ado.

**Comment by hhexiy** [comment]
hmm.. It's probably because I didn't do "ant clean" after a failed java-1.7
compile.. It doesn't seem to cause any problem in my test, but let us know
if it goes wrong.

**Comment by axch** [comment]
It?  What it?
